### ISSUE TITLE
American Psychological Association Template

### ISSUE THREAD

**Issue by joshbruce** [iainc/iA-Writer-Templates#14]
## Description

I really appreciate the inclusion of templates with the iA Writer application. The GitHub and MLA templates, I feel are great starters. Would also like to see a template for APA.

## Proposal

Create a template that follows the formatting guidelines of the [APA](http://www.apastyle.org). I am not too familiar, at this time, with how to build template for iA Writer. Therefore, this Issue is more a placeholder for me to either create it when it becomes more pressing; or, to request the creation of such a template.

Thank you for the patience (if waiting for me to do it) and consideration (if someone else would be willing to take up the charge).

**Comment by onebigclownshoe** [comment]
@joshbruce We would like to offer a template for APA in the future. We've given it some thought with respect to the future of the template system as a whole, and have decided to wait for some other functionality to be put in place. This will make the construction of an APA template easier, and will also serve as an example on how to leverage the new features.

**Comment by joshbruce** [comment]
@onebigclownshoe - Thank you. Glad to hear it is on the radar. Please feel free to close this, if it helps your internal processes.

**Comment by salutis** [comment]
@onebigclownshoe 

> We would like to offer a template for APA in the future. We've given it some thought [...] and have decided to wait for some other functionality to be put in place.

I, too, would like to use iA Writer to write APA Style papers. It has been ~4 years since this discussion took place. Do we have any news on this front?

**Comment by pichfl** [comment]
That style is quite broad in terms of possible font choices and styles. Could you provide sample documents? I think this may be a nice CSS exercise

**Comment by salutis** [comment]
@pichfl 

> Could you provide sample documents?

Take a look at the official [sample papers](https://apastyle.apa.org/style-grammar-guidelines/paper-format/sample-papers) as well as some [unofficial sample papers](https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/apa_sample_paper.html) in APA Style.

**Comment by pichfl** [comment]
I don't think all of the requirements can be achieved using the templates of iA Writer. But a lot could be covered.

**Comment by salutis** [comment]
@pichfl 

> I don't think all of the requirements can be achieved using the templates of iA Writer. But a lot could be covered.

Agree, we need to start somewhere, and an imperfect template is infinitely better than the one that does not exist.

P.S. Please note that despite the fact that more typefaces are now allowed in APA Style, the traditional New York Times typeface is widely used for APA papers, at least from what I have seen.

**Comment by broepke** [comment]
Ditto - I would love to have something close.  It doesn't have to be perfect.  My school wants APA formatted papers, they won't be super picky, but it would be nice to have this built-in as a template!

**Comment by joshbruce** [comment]
https://apastyle.apa.org/

https://apastyle.apa.org/style-grammar-guidelines/paper-format

https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/general_format.html

https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/apa_sample_paper.html

This should be helpful - all the professional papers I found were behind pay walls or web-styled. The odd part with APA is the 4+ level headers as they are sentences that are bold or bold+italic. Similar to second and third level (at least for APA 7).

**Comment by jjcurtin** [comment]
To keep the discussion going, I'd love a template that at least implemented the heading style from APA.  I find it easer to visualize the nesting of heading with the style that APA implements.   Any progress here?

**Comment by axelcme** [comment]
Just giving this a bump. APA formatting is ugly and tedious but it’s a requirement at my school.
