### ISSUE TITLE
Add night mode support for GitHub template

### ISSUE THREAD

**Issue by spier** [iainc/iA-Writer-Templates#15]
The GitHub template does not respect night mode.
See screenshot.

<img width="500" alt="github-template-night-mode" src="https://cloud.githubusercontent.com/assets/163029/20610792/2f661cd2-b29f-11e6-8b4d-40c92fecfca0.png">

**Comment by antons** [comment]
@spier Our GitHub template uses CSS extracted from GitHub. GitHub doesn’t have an official dark theme, and we decided to avoid making our own for the template. That said, we’re open to the idea.

**Comment by antons** [comment]
GitHub template in iA Writer 5.0.3 for iOS and 4.1 for macOS now includes night mode. GitHub template is also included in the app.

**Comment by spier** [comment]
That is sweet @antons. Thanks for letting me know via this issue, I might not have found this otherwise!
