### ISSUE TITLE
Templates get deleted on every app update

### ISSUE THREAD

**Issue by kurko** [iainc/iA-Writer-Templates#16]
**Problem**

Whenever I update iA Writer, the Github template that I use gets deleted.

**Possible solution**

To put templates in the `~/Library/Application Support` directory instead of `Applications`.

**Comment by antons** [comment]
@kurko Template are installed into `~/Library/Application Support` by iA Writer. Which app and system versions do you have, and how specifically do you install templates?

**Comment by kurko** [comment]
Via App Store. I installed 4.0.1 and templates vanished. Perhaps it was a unique glitch.

**Comment by antons** [comment]
@kurko Unless templates were manually placed into the application bundle, we’re not aware of anything that could cause this to happen.
