### ISSUE TITLE
Event after iA Writer Populates data attributes

### ISSUE THREAD

**Issue by cpimhoff** [iainc/iA-Writer-Templates#17]
It is difficult to edit the DOM on a document using Javascript because there is no Javascript event that iA Writer sends after it has completed replacing the `data-document` attribute with content.

For example, a user wants to have their template change the contents of all the 'h1' tags. The following snippet will not work, because the iteration through all the documents tags will be empty, they have yet to be populated by iA Writer by the time the window loads.

```javascript
window.addEventListener('load',function() {
    var headings = document.getElementsByTagName("h1");
    for(var i = 0; i < headings.length; i++){
        headings[i].innerHTML = 'changed!';
    }
});
```

The problem is then, changing the event so that the snippet runs _after_ iA Writer has populated the `data-document` tag, but it is unclear what event would satisfy that.

Is there currently a workaround or better approach? If not, iA Writer should provide a hook that always runs after iA Writer has populated the data attributes.

**Comment by antons** [comment]
iA Writer dispatches an `ia-writer-change` event to elements when it updates them with new content.

**Comment by zomars** [comment]
Sorry to bother but this code it's not executing:

```js
console.log('test'); // this logs

window.addEventListener('ia-writer-change', function() {
  console.log('test ia-writer-change'); // this doesn't
});

```
