### ISSUE TITLE
Wrong description in Helvetica template

### ISSUE THREAD

**Issue by marcthiele** [iainc/iA-Writer-Templates#18]
Hey there,

I checked the Helvetica template from your website to see how templates are done. When checking, I have seen, that at least the "style.css" file contains wrong information. It is just a minor thing, but it says:

```
/**
 * iA Writer Template “Serif”
 *
 * font-family: Helvetica
 * font-size:   15px iPhone 5, 16px iPhone 6+, 17px iPad, 18px Mac, 19px
 * line-height: 1.6316 (31px @ font-size: 19px)
 * vert margin: 31px @ 1080px wide
 */
```
… and should say that it is the Helvetica template ;)

**Comment by antons** [comment]
Thank you, we’ll update the description!
