### ISSUE TITLE
Remove header and footer margins from title page

### ISSUE THREAD

**Issue by joshua-turner** [iainc/iA-Writer-Templates#19]
We're working on our template, and on the title page we're trying to place a pseudo footer, but we're unable to place anything at the bottom of the page because the `IATemplateFooterHeight` is set to 100.

**Comment by antons** [comment]
We added an Info.plist key to disable header and footer margins on title page:

| Key | Value | Presence | Description
|:--|:--|:--|:--|
| `IATemplateTitleUsesHeaderAndFooterHeight` | Boolean | Optional | When set to NO sets header and footer height on title page to 0. Defaults to YES if absent. |
