### ISSUE TITLE
Javascript (e.g. MathJax)

### ISSUE THREAD

**Issue by luc-j-bourhis** [iainc/iA-Writer-Templates#20]
I copied the template "Modern (Sans)" shipped with iA Writer, and modified document.html to support MathJax, by adding in <head> the usual 

```
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-SVG">
    </script>
```

Then in the iOS app, in the Preview, when I switch to that new "Modern (Sans with MathJax)", I get equations rendered fine.

However, if I go back to the editor, change some text, not necessarily the equations, note, and then go back to Preview, the equations are not rendered anymore: I get the TeX code between either \\(...\\) or \\[...\\]. So the Markdown converter does what it is supposed to do but the MathJax javascript does not run.

So it seems to me that the javascript in a template is run only once. Am I missing something? Do I need to do something more clever in my template? Or is it a bug? At least, it would help if the subject of JavaScript in templates was touched upon in the documentation.

**Comment by luc-j-bourhis** [comment]
The same issue affects the MacOS application: as soon as I edit the text, the rendering of the MathJax equations disappears in the Preview pane.

**Comment by onebigclownshoe** [comment]
On when content in the editor is changed, iA Writer issues the ia-writer-change event. 
So you'll want something like this:

```javascript
window.addEventListener('load', function () {
    document.body.addEventListener('ia-writer-change', function () {
    // Do stuff here
    })
})
```

You can see this in action in the Academic template available [here](https://ia.net/writer/templates).

**Comment by mb21** [comment]
@onebigclownshoe I'm trying something similar, also changing the document with `innerHTML` inside the `load` and `ia-writer-change` callbacks, but it seems to work only in the preview. When I try to print or export to PDF on my Mac, there seems to be race conditions and the changes aren't applied. Do you know of any way to fix this?

**Comment by mb21** [comment]
Solved it. The trick was to move the JavaScript inside the `<head>` of document.html, not the `<body>`.
