### ISSUE TITLE
Support more attributes on document page

### ISSUE THREAD

**Issue by luc-j-bourhis** [iainc/iA-Writer-Templates#22]
The use case I have in mind is a document page template like
```html
<body>
    <header>
        <h1 data-title></h1>
        <h2 data-author></h2>
    </header>
    <main data-document>&nbsp;</main>
</body>
```
I compose way more notes in iA Writer than I export or print them, and therefore it is important that iA Writer also provides a nice reading experience on its own.

**Comment by antons** [comment]
Thank you for the suggestion. We’ll look into this for a future update.

**Comment by antons** [comment]
`data-title`, `data-author`, and `data-date` are now available on all pages.
