### ISSUE TITLE
Is there a way to target inverted preview in night-mode with css?

### ISSUE THREAD

**Issue by Jobbies** [iainc/iA-Writer-Templates#23]

**Comment by antons** [comment]
No. What specifically would you like to do, and why?

**Comment by Jobbies** [comment]
I styled night-mode in the template that I am making.

![night-mode](https://user-images.githubusercontent.com/142909/27169696-4e16ca98-51ee-11e7-8891-59c12faa4159.png)

When the preview is inverted the styles turn dull like the below image and I am unsure where those styles come from.

![invert](https://user-images.githubusercontent.com/142909/27169826-f1e1cac4-51ee-11e7-9849-989d2447e0b9.png)

**Comment by antons** [comment]
It’s hard to tell what specifically causes this without seeing the template CSS. Did you set up colors as recommended in documentation?

```
iA Writer adjusts Preview toolbar colors to match the currently visible template on macOS. Be sure to set color and background-color on the <html> element.
```

Background color should be opaque.

**Comment by Jobbies** [comment]
Thanks @antons that is exactly what I was missing. The template I am making can be found here [SDS-iA-Writer-template](https://github.com/Jobbies/SDS-iA-Writer-template)
