### ISSUE TITLE
“Invalid Template” when installing templates from iCloud Drive on iOS with version 5.0.2

### ISSUE THREAD

**Issue by luc-j-bourhis** [iainc/iA-Writer-Templates#26]
I developed a template ("Geek" [here](https://github.com/luc-j-bourhis/iA-Writer-Templates/tree/new_templates)) which used to work fine with iA Writer on both MacOS and iOS. I haven't used the latter in a while so I don't know which version broke my template but I can't load it anymore on iOS, systematically getting an "Invalid Template" error. It loads fine on MacOS on the contrary. Has something changed recently in the way to write templates?

**Comment by antons** [comment]
I was able to successfully install the Geek template on my iPhone with iA Writer 5.0.3 by AirDropping in from my Mac. It loads and renders without any issues.

If you getting the invalid template bundle when attempting to install the template: how specifically are you installing the template?

**Comment by luc-j-bourhis** [comment]
I copied it to iCloud Drive, then from my iPad Air, I went to Files, and tapped on the template icon: it opened in iA Writer with the error I reported. Meanwhile I tried something else: zip it and put it on a web server, then open it in Safari: I am given the choice to open it in iA Writer, and it gets installed successfully. I haven’t tried with Air Drop as my MAC don’t support that.

**Comment by antons** [comment]
@luc-j-bourhis Thank you for reporting this! We fixed the issues preventing template installation from iCloud Drive, and will release them with the next update.
