### ISSUE TITLE
Preview print version?

### ISSUE THREAD

**Issue by thedamon** [iainc/iA-Writer-Templates#27]
I wanted to do some updates to the exported pdf version of a template and found the update process very intimidatingly long and time-consuming.

It essentially amounted to:

1. update code, save
2. close iaWriter (bc it wasn't picking up changes without relaunch)
3. run template file, confirm installation, which reopened iaWriter
4. export the doc (cmd+shift+E, click, ENTER to save)
5. open exported file to look at results and assess code update.

I'd be curious about a 2 step process if one is possible? (also, is it expected that I need to relaunch iaWriter to see updates to installed template show up in exports?)

**Comment by antons** [comment]
iA Writer copies installed templates to its application support folder. You can Control-click templates in Preferences to show them in Finder. Edit the installed copy directly, and iA Writer will pick up changes on export.

WebKit inspector has a print mode which should speed up testing for many changes to document page. When editing the installed template, you can refresh preview with `⇧⌘R`. 

<img src="https://user-images.githubusercontent.com/129705/34491215-4ab73ec8-efeb-11e7-9a5e-cdfee7e1c5b7.png" width=800>
