### ISSUE TITLE
Title cut to one page?

### ISSUE THREAD

**Issue by lsinger** [iainc/iA-Writer-Templates#3]
Hi there! 

I'm trying to use the title page to add a blank page between the title and the document (without adding to the page count). 

I experimented a bit with `page-break-before` and `page-break-after`. Unfortunately though it seems that Writer cuts off the title to a single page before merging the compiled documents. What can I do to extend my title page to two pages? 

Thanks in advance!

**Comment by antons** [comment]
Your observation is correct. Currently, iA Writer uses only one page from the title HTML. We’ll keep your use case in mind as we improve templates. Thank you for mentioning it.

**Comment by lsinger** [comment]
For context — I'd like to use the PDF to bind a book as described here: http://www.cheapimpostor.com/dayinlife/index.html

**Comment by antons** [comment]
Very cool project! Thank you for the additional context — it helps.
