### ISSUE TITLE
How to uninstall a template?

### ISSUE THREAD

**Issue by AeonFr** [iainc/iA-Writer-Templates#30]
I'm really sorry if this question is not ment to be here! I'm looking for a way to uninstall a template. Templates installed through `File>Install Template` are not listed in `iA Writer\Templates` (where `iA Writer` is the installation folder). I need to be able to uninstall templates, as part of the trial/error process necessary to develop a new one. Where can I uninstall them from?

**Comment by onebigclownshoe** [comment]
On Windows, you can delete the template from `C:\Users\{your username}\AppData\Roaming\iA Writer\Templates` and then restart the app.
