### ISSUE TITLE
Using HeaderHeight and FooterHeight is not working

### ISSUE THREAD

**Issue by AeonFr** [iainc/iA-Writer-Templates#31]
I developed a simple theme in iA Writer for Windows. Code is just the same as in Example template, just changed the naming properties in the `Info.plist` file and added to `style.css` this code:

```
html {
  font-family: 'Bahnschrift', 'Segoe UI', sans-serif;
  color: #444;
  font-weight: 300;
  font-size: 18px; }

html.night-mode {
  background-color: #444;
  color: white; }

a {
  text-decoration: none;
  color: #777;
  font-weight: bolder; }

th {
  padding: .25em .5em; }

td {
  padding: .25em 0;
  border-bottom: 1px solid #ccc; }

```
Somehow, however, my template seems to be working really bad. 
- Page numbers don't work
- Content is sticked to the top and bottom of the page (no margins)
- Table headers that are overlapped when there's a page break inside the table (image below)
- For some reason the "font-weight: 300" CSS declaration works in the preview window but not in the exported PDF.

![example](https://user-images.githubusercontent.com/11742754/40117096-25a75a8e-5916-11e8-9985-5ce8d03e60a0.png)

Just to try, I rendered the same document using the `PlexSans` template and the table headers are still buggy. So this most likely is an iA Writer issue and not something specific to my template's code.

PS:\
I wasn't really needing to render the table in two pages, I was just adding the table to see if the page numbers would show if there were more than one page in the document.

For now I can use my template as I wanted to, but to do so I have to use small hacks, for example adding `style="heght:30px"` somewhere in the `header.html` and `footer.html` files,  or `margin-top: 30mm;` in the CSS, and disabling page numbers.

This bugs are not really something that affect my current project, but there are features that in the future I might want to use.

I love iA Writer because...

Before iA Writer, my workflow to get PDF out of markdown files was:
- Open the file in Visual Studio Code
- Render to HTML with styles using a plug-in and a custom stylesheet I wrote
- Open in Edge (for some reason is the best browser regarding printing capabilities - for example the only one that supports the CSS `page-break` property without bugs)
- Open the print dialog in Edge and select "Print to PDF"

With just some minor improvements in iA Writer, I could have and awesome markdown editor and export files directly to PDF using my custom stylesheet with just two steps:
- Open the file in iA Writer
- File -> Export -> PDF

So I would really like to see the export to PDF feature with some improvements!

But in the meantime, might I suggest a simple workaround that might do the trick? (at least for me)\
When I use the "File->Export->HTML" option, **would it be possible that in the generated HTML file, the stylesheet of my template got injected in a `<style>` tag?** That way I would still easily fall back to the "Print" option of the browser.

And please, keep up the good work! I'm a big fan of iA Writer. Cheers

**Comment by jflepp** [comment]
Is there still progress being made here?

**Comment by onebigclownshoe** [comment]
Version 1.2 of Windows completely changed how templates are rendered to bring it closer in line with Mac/iOS. It is now using Chromium instead of IE as the engine.

If there are any bugs outstanding, they will be wholly new so please create a new issue for each.
