### ISSUE TITLE
The `ia-writer-change` event is not firing

### ISSUE THREAD

**Issue by zomars** [iainc/iA-Writer-Templates#32]
I have this basic code:

```js
console.log('test'); // this logs

window.addEventListener('load', function() {
  console.log('test load'); // this logs too
});

document.addEventListener('ia-writer-change', function() {
  console.log('test ia-writer-change'); // this doesn't log
});
```

Since I couldn't find any docs on JS events from iAWriter I couldn't figure if I'm doing something wrong.

**Comment by antons** [comment]
iA Writer dispatches an `ia-writer-change` only to the specific elements that are updated with new content. That is elements which have one of the `data` attributes: `data-document` (on the document page) or `data-author`, `data-date`, `data-page-count`, `data-page-number` (on the title, header, and footer pages).

**Comment by zomars** [comment]
Thanks for the clarification, maybe we could document this somewhere in the README. I can confirm that this code is working:
```js
var documentBody = document.querySelector('[data-document]');

documentBody.addEventListener('ia-writer-change', function() {
  console.log('test ia-writer-change');
});
```
