### ISSUE TITLE
ia-writer-change and night-mode change

### ISSUE THREAD

**Issue by 54wedge** [iainc/iA-Writer-Templates#34]
Hi.I am trying to write a javascript that can return different config option based on the appearance. I have
```
var get_mode = function() {
  var html = document.getElementsByTagName('html')[0]
  if(html.classList.contains('night-mode')){
    var config = {theme:"dark"}
  }
  else{
    var config = {theme:"default"}
  }
  return config
}
```
and
```
window.addEventListener('load', function () {
  console.log('loaded')
  document.body.addEventListener('ia-writer-change',function(){
    console.log(get_mode())
    console.log('changed')
  })
})
```
However, this code will partially work. It will only work when switching from dark to light appearance with shift-command-R. Otherwise, I have to open another file and go back when switching from light to dark appearance. Is there any way to detect appearance switching from dark to light or vice verse?

**Comment by antons** [comment]
We recommend using a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/MutationObserver) to listen to changes to element’s attributes. This [StackOverflow answer](https://stackoverflow.com/a/53914092) includes a drop-in solution.
