### ISSUE TITLE
Changes to custom template not reloading

### ISSUE THREAD

**Issue by lukejanicke** [iainc/iA-Writer-Templates#35]
Changes to my custom template are not reloading when I enter <kbd>Shift</kbd> + <kbd>Command</kbd> + <kbd>R</kbd>. I have enabled Web Inspector in Preview and confirmed that changes to the style sheet are not propagating. To see changes, I have to reinstall the template, and then still have to enter <kbd>Shift</kbd> + <kbd>Command</kbd> + <kbd>R</kbd> before the changes are visible. I can’t develop like this. Is there anything I’m missing?

**Comment by antons** [comment]
iA Writer copies templates to its Application Support directory when installed. It sounds like you may be editing the template at its original location, rather than the installed copy. You can right-click the templates in Preferences → Templates and Show in Finder to edit the template.
