### ISSUE TITLE
GitHub Template Causes Issue Exporting to PDF on Windows

### ISSUE THREAD

**Issue by TheBigNeo** [iainc/iA-Writer-Templates#36]
If I want to export the document with the Windows client, I get the following error message

https://snipboard.io/NSyesQ.jpg

**Comment by onebigclownshoe** [comment]
Could you please tell me which version of Windows you are using and which version of iA Writer?
(In the Help menu > About iA Writer > Double click on the version number to copy it)

**Comment by onebigclownshoe** [comment]
Also, do you see this with all documents or just one in particular? And which template is being used in the Preview?

**Comment by TheBigNeo** [comment]
iA: 1.1.7121.15952 
Windows: Windows 10 Version 1903 Build 18362.295

The preview is set to GitHub, otherwise I cannot export the PDF as GitHub.
It happens with all documents. If I switch to a different template the export works

**Comment by onebigclownshoe** [comment]
This is resolved in version 1.2.
