### ISSUE TITLE
Template location

### ISSUE THREAD

**Issue by cpshanley** [iainc/iA-Writer-Templates#39]
Where are the templates stored on macOS?

thx

**Comment by antons** [comment]
They are stored in `~/Containers/pro.writer.mac/Data/Library/Application Support/iA Writer/Templates/`. You can right-click the templates in Preferences → Templates and select Show in Finder.

**Comment by cpshanley** [comment]
Hi,

Thanks for that. But it is for user templates. I should have been clearer. What I want is to use one of IA’s built in templates (Duo) as a starting point for my own.


Cheers,
Colin

**Comment by antons** [comment]
Built-in templates are store in `iA Writer.app/Contents/Resources/Templates`.

**Comment by rgcarr** [comment]
For those stumbling across this post (via Google, as I do) every few months, the location of the user's/custom templates on macOS 13.x is `~/Library/Containers/pro.writer.mac/Data/Library/Application Support/iA Writer/Templates`

As previously reported, the inbuilt templates are still at `/Applications/iA Writer.app/Contents/Resources/Templates`

Custom templates is probably one area of iA Writer that could do with some improvement - not only general management and usability, but developing/testing is a bit of a drag.
