### ISSUE TITLE
Content to the left or right of the document text on each page

### ISSUE THREAD

**Issue by mb21** [iainc/iA-Writer-Templates#4]
Is there a way to display something on the left or right of the document text on each page?

Ideally, iA Writer Templates would support the [Paged Media CSS module](https://www.w3.org/TR/css3-page/), where I could use the `@left` and `@right` selectors. Paged Media is implemented [in PrinceXML](http://www.princexml.com/doc/paged/#page-header-footer) and [WeasyPrint](http://weasyprint.org/) among [others](https://www.print-css.rocks/tools.html)...

**Comment by antons** [comment]
Currently, there’s no way to do this in iA Writer. While we cannot promise to implement the full Paged Media CSS module (this a job for [WebKit](https://bugs.webkit.org/show_bug.cgi?id=15548)), we will definitely consider adding ability to position content to the left or right of the document page for a future update.

**Comment by mb21** [comment]
Thanks for the prompt reply!

oh well, that bug report is from 2007 and still not fixed, so I'm not holding my breath.

I guess you're stuck with webkit because you are using the iOS/macOS built-in webview? This seems to make a lot of sense for the preview, but not so much for the PDF/print generation... In fact, I'm wondering how you got webkit to do the headers and footers, since `position: fixed` doesn't work for that any more, if I'm not mistaken...?

**Comment by antons** [comment]
You’re welcome. We prefer a pragmatic approach.
