### ISSUE TITLE
Change heading format in editor?

### ISSUE THREAD

**Issue by sogen** [iainc/iA-Writer-Templates#40]
note: Not in templates, but in Editor

Is there a way to change the font weight of a header such as H3 to Regular?
<img width="610" alt="Screen Shot 2020-03-24 at 9 35 AM" src="https://user-images.githubusercontent.com/2784323/77452183-e1e97080-6db2-11ea-9707-4a80ae5e8620.png">

**Comment by antons** [comment]
There’s no way to this. In the future, please direct questions not related to templates to support@ia.net.
