### ISSUE TITLE
Header Height and Footer Height unit

### ISSUE THREAD

**Issue by 54wedge** [iainc/iA-Writer-Templates#45]
Hi,
I am on macOS version 10.15.4 and using the IA writer version 5.6.3. It seems like the unit for header height and footer height is in `pt` instead of the documented `px`. I am using left and right margin of 1 inch. Setting the height to 96 should result exactly 1 inch margin on the top and bottom. However, the result margin looks longer than it should be. I experimented a bit and find out that setting the height to 72 results a margin close to 1 inch, which implies that the unit might be `pt` instead of `px`
![height](https://user-images.githubusercontent.com/20142690/96802497-f4bf3480-13d7-11eb-8c07-75d549d1c081.png)

**Comment by antons** [comment]
Thank you for reporting the issue. You‘re correct, it’s in points. We updated the documentation.
