### ISSUE TITLE
Date Locale, full month names

### ISSUE THREAD

**Issue by getflourish** [iainc/iA-Writer-Templates#47]
How’s the locale for displaying a date determined? My system language is German.

When I use 

```
<span data-date="d.MMMM YYYY"></span>
```

The date gets displayed as: `17 February 2021` but I would expect it to be `17. Februar 2021`.

My macOS is set to German and I’ve also tried to set a `lang="de"` on the `header.html`

**Comment by antons** [comment]
Thank you for reporting the issue! We fixed this in iA Writer 6.0.
