### ISSUE TITLE
Access content blocks from within templates

### ISSUE THREAD

**Issue by ulfschneider** [iainc/iA-Writer-Templates#49]
Hi,
I have this [template to write letters](https://ulf.codes/tools/ia-letter/). Sender and receiver are defined in a definition list – see the @sender and @receiver notation. Do you think it´s possible to combine that somehow with your content blocks, so that I can refer to pre-defined addresses which are stored in content blocks? E.g. is there a way to access a content block API from within the template?

**Comment by onebigclownshoe** [comment]
I'm not sure I understand where you want the template to become involved. It is certainly possible to store any addresses in an alternate file and then reference that at the top of your document. But it sounds like you want to do more than that?

**Comment by ulfschneider** [comment]
My template allows to define a sender and a receiver address in the form:

@receiver
:Ernie English
:78 Reading Lane
:34567 Read City

If I´d use a placeholder instead of the address, like

@receiver
:/ernie

that /ernie placeholder should link to a content block that contains the address of Ernie English and I assume to handle the content block inside my template correctly, I would need to have access to a content block API from within the template, to load the data, and position it.

**Comment by onebigclownshoe** [comment]
Content blocks are processed before any of your JS will run. So you can simply:

```
ernie.md
```

where the file contains both your syntax and the address:

```
@receiver
:Ernie English
:78 Reading Lane
:34567 Read City
```

**Comment by ulfschneider** [comment]
Thank you, that is great. I do it now this way:

@receiver
/ernie.md

and ernie.md is

:Ernie English
:78 Reading Lane
:34567 Read City

because the address shouldn´t store the information about if it´s a sender or receiver address.

I wonder why I didn´t try that. Anyway, that´s a solution for me. Thank you again.
