### ISSUE TITLE
Numbering chapters without including numbers in chapter titles

### ISSUE THREAD

**Issue by russellbits** [iainc/iA-Writer-Templates#50]
i am working on a book with numbered chapters. Right now, to keep it organized, I title the files themselves "1. Meet Able.md" on through "12. The Return of Waca and Rilla.md" This keeps the chapters in order in the library. However, when I go to include `data-title` in the template header.html file, of course, I get the number, which I do not want. The manuscript itself is built using one document that has `/01.meet-able.md` through `/12.the-return-of-waca-and-rilla.md` The Chapter numbers and titles are re-written into each document using markdown, as opposed to say, frontmatter. So, this is just a general question of if there is a better way to to do what I am doing? Should I organize the chapters in some other way? Can I use frontmatter and insert the data into template files? That would be ideal.

**Comment by russellbits** [comment]
By the way, if anyone would care to investigate/read the book, it's here on Github:
https://github.com/russellbits/Writing/tree/master/Fiction/04.novels/03.brother-dustfish

**Comment by antons** [comment]
Sorry about the late response! It is now possible (since iA Writer 6.0) to provide `title` metadata at the beginning of documents:

```
---
Title: The Return of Waca and Rilla
---
```

**Comment by antons** [comment]
I must note, however, that when chapters are combined together into one document using content blocks, the footer will show the document title, rather than chapter titles, becase documents are converted HTML first, and rendered as PDFs after.
