### ISSUE TITLE
Q: Is it possible to add a div with a class within a template ...?

### ISSUE THREAD

**Issue by seanvosler** [iainc/iA-Writer-Templates#57]
Example...

"after every H1 add <div class="content">"

and close... 

"before every H1 add </div>"

I know in the docs it mentions you can execute javascript in templates, but not seeing how that's possible... would you add an example.js file to the template and call it in the heading of the document?

**Comment by onebigclownshoe** [comment]
> would you add an example.js file to the template and call it in the heading of the document?

Yes. Your code will then need to be run on each update of the document (since it is recreated with each keystroke in Editor).
So your example.js file should contain something like this:
```
window.addEventListener('load', function () {
    document.body.addEventListener('ia-writer-change', function () {
    // Do stuff here
    })
})
```
