### ISSUE TITLE
Web preview doesn’t update data-attributes

### ISSUE THREAD

**Issue by esundahl** [iainc/iA-Writer-Templates#59]
The documentation says that the `data-title` should work on all pages, however `data-title` element is not being updated and the `ia-writer-change` event is never fired in the web preview.

Writer Version: 6.0.4 (60081)
OS: MacOS 12.6

```html
// document.html

<body>
    <h1 data-title>// Not properly filled</h1>
    <div data-document>// Content is properly filled</div>
    <script>
        const content = document.querySelector('[data-document]')
        content.addEventListener('ia-writer-change', function (e) {
            // This fires
            console.log('ia-writer-change: [data-document]', e)
        })

        const title = document.querySelector('[data-title]')
        title.addEventListener('ia-writer-change', function (e) {
            // This does not fire
            console.log('ia-writer-change: [data-title]', e)
        })
    </script>
</body>
```

**Comment by antons** [comment]
Thank you for reporting the issue! We’ll correct this in iA Writer 6.0.6 (60099). You’re welcome to join iA Writer beta program to get access to the build before general availability. If you’re interested, please email beta+writer@ia.net and mention this issue.

**Comment by antons** [comment]
iA Writer 6.0.6 is now available on the App Stire.
