### ISSUE TITLE
Can custom templates export to Microsoft Word / .docx files?

### ISSUE THREAD

**Issue by avk** [iainc/iA-Writer-Templates#61]
I write fiction in iA Writer (thanks for the lovely tool). I'd like to export work into [Manuscript Format](https://www.shunn.net/format/story/), which is a Word doc with some basic formatting constraints.

Can a custom template help or is that limited to HTML and PDF? Any thoughts on how to accomplish this?

My current approach is a laborious 

1. File > Export > Word
2. open Word doc
3. change fonts
4. add double spacing
5. indent all paragraphs
6. center every "#" sign
7. … etc.

It's the steps from 3 on that I'd love reduce / automate.

**Comment by antons** [comment]
@avk Microsoft Word has its own templating system, and it supports [applying templates to existing documents](https://www.google.com/search?q=word+apply+template+to+existing+document).

**Comment by avk** [comment]
Thanks. So, it sounds like there's no ability for an iA Writer custom template to export to Word [with a Word template]?
