### ISSUE TITLE
Wrong data-page-count?

### ISSUE THREAD

**Issue by cadonau** [iainc/iA-Writer-Templates#8]
I’m including the current page number as well as the total page count in the footer of my template. When trying to print or export the document to PDF—without including a title page—the total page count seems to be off by one. Instead of the expected “1 / 1” it would say “1 / 2”. Is that a known issue, or could it have to do with the CSS counters I’m using for a couple heading tags?

**Comment by antons** [comment]
`data-page-count` is, indeed, off by one on macOS. We’ll fix it in the next update. Thank you for reporting the issue.
