### ISSUE TITLE
How to access metadata

### ISSUE THREAD

**Issue by ponychicken** [iainc/iA-Writer-Templates#9]
According to [your docs](https://ia.net/writer/support/general/markdown-guide#multimarkdown) Writer can process MultiMarkdown metadata. How do I access it inside of a template?

**Comment by antons** [comment]
Currently, the processing option applies to MultiMarkdown, not iA Writer. Metadata is processed inside `data-document`, but it can’t be accessed by static template files. We would like to improve this in the future.

**Comment by mb21** [comment]
But can we access it through JavaScript inside the template?

**Comment by antons** [comment]
@mb21 That is a good idea. Thank you!

**Comment by ponychicken** [comment]
@mb21 could you expand on this javascript idea?

**Comment by antons** [comment]
@mb21 It’s possible to hack it in by extracting metadata from `data-document` on `ia-writer-change`, but it’s not trivial.

**Comment by thespacedoctor** [comment]
@antons Can you give us a little more direction with extracting metadata from `data-document` on `ia-writer-change`? I would like to get at my MMD metadata ;)

**Comment by marcammann** [comment]
Not @antons but what I did was create divs at the top of my document with the interpolated value of the metadata and then accessed the DOM element after the `ia-writer-change` event.

You'll also have to hide the elements in your styles:

```
Title: Test

<div class="meta" id="title">[%Title]</div>
<div class="meta" id="brand">[%Brand]</div>
```

`document.getElementById('title').innerText === "Test"`

**Comment by thespacedoctor** [comment]
Thanks @marcammann 

Let's say I have this metadata at the top of my MMD document:

```text
title: my lovely horse
author: Neil Hannon
tags: #horse #song
```

Here's what I did in the end to access hashtags from the metadata.

1. Turn off 'Process Metadata' in preferences so metadata gets rendered within paragraph elements at the top of the body:

    ![](https://farm8.staticflickr.com/7896/46278876024_e459a4a0d4_o.png)

2. Parse the hashtags within javascript. I was only trying to access the tags, but you can use this method to parse out whatever MMD metadata you want:

    // EXTRACT HASH-TAGS AND PRESENT THEM IN HTML RENDERING
    var processHashTags = function() {
        
        // GET HASH TAGS
        tagSpans = document.getElementsByClassName('hashtag')
        tags = []
        for (var i = 0; i < tagSpans.length; i++) {
            tags.push(tagSpans[i].innerHTML.replace("#", ""));
        }

        // METADATA IS IN PARAGRAPHS BEFORE FIRST HEADER
        var c = document.body.childNodes;
        for (var i = 0; i < c.length; i++) {
            if (c[i].nodeName == "H1") {
                break
            }
            if (c[i].nodeName == "P") {
                if (c[i].innerHTML.includes(":")) {
                    c[i].remove()
                }
            }
        }

        // ADD LINKED HASH TAGS
        var tagsContainer = document.createElement('div')
        tagsContainer.setAttribute('class', 'tags')
        for (var i = 0; i < tags.length; i++) {
            tagsContainer.innerHTML += '<a href="ia-writer://quick-search?query=%23' + tags[i] + '" class="hashtag">#' + tags[i] + '</a>  '
        }

        return [tags, tagsContainer]
    }

**Comment by thespacedoctor** [comment]
Thanks @marcammann 

Let's say I have this metadata at the top of my MMD document:

```text
title: my lovely horse  
author: Neil Hannon  
tags: #horse #song  
```

**NOTE STRICT DOUBLE SPACE AT END OF METADATA LINES**

Here's what I did in the end to access hashtags from the metadata.

1. Turn off 'Process Metadata' in preferences so metadata gets rendered within paragraph elements at the top of the body:

    ![](https://farm8.staticflickr.com/7896/46278876024_e459a4a0d4_o.png)

2. Parse the hashtags within javascript. I was only trying to access the tags, but you can use this method to parse out whatever MMD metadata you want:

    ```javascript
    // EXTRACT HASH-TAGS AND PRESENT THEM IN HTML RENDERING
    var processHashTags = function() {
        
        // GET HASH TAGS
        tagSpans = document.getElementsByClassName('hashtag')
        tags = []
        for (var i = 0; i < tagSpans.length; i++) {
            tags.push(tagSpans[i].innerHTML.replace("#", ""));
        }

        // METADATA IS IN PARAGRAPHS BEFORE FIRST HEADER
        var metadict = {}
        var c = document.body.childNodes;
        for (var i = 0; i < c.length; i++) {
            if (c[i].nodeName == "H1") {
                break
            }
            if (c[i].nodeName == "P" && c[i].innerHTML.includes(":")) {
                var dataelements = c[i].innerHTML.split("<br>")
                for (var j = 0; j < dataelements.length; j++) {
                    keyvalue = dataelements[j].trim().split(":")
                    metadict[keyvalue[0].trim()]=keyvalue[1].trim()
                }
            }
        }

        // ADD LINKED HASH TAGS
        var tagsContainer = document.createElement('div')
        tagsContainer.setAttribute('class', 'tags')
        for (var i = 0; i < tags.length; i++) {
            tagsContainer.innerHTML += '<a href="ia-writer://quick-search?query=%23' + tags[i] + '" class="hashtag">#' + tags[i] + '</a>  '
        }

        return [tags, tagsContainer, metadict]
    }
    ```

    Note that the `tagsContainer` element here contains your hashtags that are linked to an iA search for those specific tags (super handy in rendered docs).

3. Finally call `processHashTags` to access all your metadata (e.g. `metadata["title"]`) :

    ```javascript
    // WAIT FOR THE 'ia-writer-change' EVENT BEFORE ACTING
    document.body.addEventListener('ia-writer-change', function() {
        var dataArray = processHashTags();
        var metadata = dataArray[2];
    })
    ```
